// Writes supabase/seed.sql from the in-code articles, team and policies.
// Run with: npx tsx --tsconfig tsconfig.json scripts/generate-supabase-seed.ts
import { writeFileSync } from 'node:fs';
import { knowledgeArticles } from '../src/data/knowledgeArticles';
import { staticPolicies, staticTeamMembers } from '../src/data/siteContent';

const text = (value: string) => `'${value.replace(/'/g, "''")}'`;
const textArray = (values: string[]) => (values.length ? `array[${values.map(text).join(', ')}]::text[]` : `'{}'::text[]`);

const articles = knowledgeArticles.map((article, index) => `insert into public.articles
  (slug, title, seo_title, description, topic, image_url, image_alt, image_credit, ingredients, keywords, key_points, body, status, published_at, created_at)
values (
  ${text(article.slug)}, ${text(article.title)}, ${article.seoTitle ? text(article.seoTitle) : 'null'}, ${text(article.description)}, ${text(article.topic)},
  ${text(article.image.src)}, ${text(article.image.alt)}, ${text(article.image.photographer)},
  ${textArray(article.ingredients)}, ${textArray(article.keywords)}, ${textArray(article.keyPoints)},
  ${text(article.body.trim())},
  'published', ${text(article.published)}, now() - interval '${index} seconds'
) on conflict (slug) do nothing;`);

const team = staticTeamMembers.map((member, index) => `insert into public.team_members (name, role, bio, image, sort_order)
select ${text(member.name)}, ${text(member.role)}, ${text(member.bio)}, ${text(member.image)}, ${index}
where not exists (select 1 from public.team_members where name = ${text(member.name)});`);

const policies = staticPolicies.map((policy) => `insert into public.policies (id, title, content, effective_date)
values (${text(policy.id)}, ${text(policy.title)}, ${text(policy.content)}, ${text(policy.effectiveDate || policy.lastUpdated)})
on conflict (id) do nothing;`);

const sql = `-- Generated by scripts/generate-supabase-seed.ts. Safe to run more than once.
-- Article order on the site follows published_at, then created_at (newest first).

${articles.join('\n\n')}

${team.join('\n\n')}

${policies.join('\n\n')}
`;

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql);
console.log(`Wrote supabase/seed.sql: ${knowledgeArticles.length} articles, ${staticTeamMembers.length} team members, ${staticPolicies.length} policies.`);
